### ISSUE TITLE
[BUG] Broken link in the about section of this repo.

### ISSUE THREAD

**Issue by RuthwikReddy09** [mithilp/centerstage-ftc-scorer#8]
The deployment link which is in the about section of this repo is broken. It displays a 404 Not Found error.

[screen-capture (1).webm](https://github.com/mithilp/centerstage-ftc-scorer/assets/126862059/f15b9b06-9dc1-4d5a-bba0-e2d6e7cbb4eb)

**Comment by mithilp** [comment]
Thanks for pointing that out! Just fixed it and changed it to the correct URL: https://ftcscorer.vercel.app
